version: '3'

services:
    mongodb:
        image: mongo:4.4
        ports:
            - 27017:27017 
        volumes:
            - ./mongodb:/data/db:z
        environment:
            MONGO_INITDB_DATABASE: spyface