apiVersion: batch/v1
kind: Job
metadata:
  name: train-job
spec:
  template:
    spec:
      containers:
        - name: spyface-train
          image: gcr.io/the-vops/treino:0.2
          volumeMounts:
            - mountPath: /opt/modelo
              name: pasta-modelo
      restartPolicy: OnFailure
      volumes:
        - name: pasta-modelo
          persistentVolumeClaim:
            claimName: pvc-nfs